/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TagsRouteImport } from './routes/tags'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as HabitsRouteImport } from './routes/habits'
import { Route as GanttRouteImport } from './routes/gantt'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as FlaggedRouteImport } from './routes/flagged'
import { Route as CompletedRouteImport } from './routes/completed'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BoardRouteImport } from './routes/board'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OauthCallbackRouteImport } from './routes/oauth.callback'
import { Route as ProjectsTypeIdRouteImport } from './routes/projects.$type.$id'

const TagsRoute = TagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsRoute = HabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => rootRouteImport,
} as any)
const GanttRoute = GanttRouteImport.update({
  id: '/gantt',
  path: '/gantt',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const FlaggedRoute = FlaggedRouteImport.update({
  id: '/flagged',
  path: '/flagged',
  getParentRoute: () => rootRouteImport,
} as any)
const CompletedRoute = CompletedRouteImport.update({
  id: '/completed',
  path: '/completed',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsTypeIdRoute = ProjectsTypeIdRouteImport.update({
  id: '/$type/$id',
  path: '/$type/$id',
  getParentRoute: () => ProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/calendar': typeof CalendarRoute
  '/completed': typeof CompletedRoute
  '/flagged': typeof FlaggedRoute
  '/forecast': typeof ForecastRoute
  '/gantt': typeof GanttRoute
  '/habits': typeof HabitsRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/tags': typeof TagsRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/projects/$type/$id': typeof ProjectsTypeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/calendar': typeof CalendarRoute
  '/completed': typeof CompletedRoute
  '/flagged': typeof FlaggedRoute
  '/forecast': typeof ForecastRoute
  '/gantt': typeof GanttRoute
  '/habits': typeof HabitsRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/tags': typeof TagsRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/projects/$type/$id': typeof ProjectsTypeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/calendar': typeof CalendarRoute
  '/completed': typeof CompletedRoute
  '/flagged': typeof FlaggedRoute
  '/forecast': typeof ForecastRoute
  '/gantt': typeof GanttRoute
  '/habits': typeof HabitsRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/tags': typeof TagsRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/projects/$type/$id': typeof ProjectsTypeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/board'
    | '/calendar'
    | '/completed'
    | '/flagged'
    | '/forecast'
    | '/gantt'
    | '/habits'
    | '/inbox'
    | '/login'
    | '/projects'
    | '/review'
    | '/settings'
    | '/tags'
    | '/oauth/callback'
    | '/projects/$type/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/board'
    | '/calendar'
    | '/completed'
    | '/flagged'
    | '/forecast'
    | '/gantt'
    | '/habits'
    | '/inbox'
    | '/login'
    | '/projects'
    | '/review'
    | '/settings'
    | '/tags'
    | '/oauth/callback'
    | '/projects/$type/$id'
  id:
    | '__root__'
    | '/'
    | '/board'
    | '/calendar'
    | '/completed'
    | '/flagged'
    | '/forecast'
    | '/gantt'
    | '/habits'
    | '/inbox'
    | '/login'
    | '/projects'
    | '/review'
    | '/settings'
    | '/tags'
    | '/oauth/callback'
    | '/projects/$type/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardRoute: typeof BoardRoute
  CalendarRoute: typeof CalendarRoute
  CompletedRoute: typeof CompletedRoute
  FlaggedRoute: typeof FlaggedRoute
  ForecastRoute: typeof ForecastRoute
  GanttRoute: typeof GanttRoute
  HabitsRoute: typeof HabitsRoute
  InboxRoute: typeof InboxRoute
  LoginRoute: typeof LoginRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ReviewRoute: typeof ReviewRoute
  SettingsRoute: typeof SettingsRoute
  TagsRoute: typeof TagsRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habits': {
      id: '/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof HabitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gantt': {
      id: '/gantt'
      path: '/gantt'
      fullPath: '/gantt'
      preLoaderRoute: typeof GanttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flagged': {
      id: '/flagged'
      path: '/flagged'
      fullPath: '/flagged'
      preLoaderRoute: typeof FlaggedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/completed': {
      id: '/completed'
      path: '/completed'
      fullPath: '/completed'
      preLoaderRoute: typeof CompletedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$type/$id': {
      id: '/projects/$type/$id'
      path: '/$type/$id'
      fullPath: '/projects/$type/$id'
      preLoaderRoute: typeof ProjectsTypeIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsTypeIdRoute: typeof ProjectsTypeIdRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsTypeIdRoute: ProjectsTypeIdRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardRoute: BoardRoute,
  CalendarRoute: CalendarRoute,
  CompletedRoute: CompletedRoute,
  FlaggedRoute: FlaggedRoute,
  ForecastRoute: ForecastRoute,
  GanttRoute: GanttRoute,
  HabitsRoute: HabitsRoute,
  InboxRoute: InboxRoute,
  LoginRoute: LoginRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  ReviewRoute: ReviewRoute,
  SettingsRoute: SettingsRoute,
  TagsRoute: TagsRoute,
  OauthCallbackRoute: OauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
