/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTagsRouteImport } from './routes/_app/tags'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppReviewRouteImport } from './routes/_app/review'
import { Route as AppProjectsRouteImport } from './routes/_app/projects'
import { Route as AppLocationRouteImport } from './routes/_app/location'
import { Route as AppInboxRouteImport } from './routes/_app/inbox'
import { Route as AppForecastRouteImport } from './routes/_app/forecast'
import { Route as AppFlaggedRouteImport } from './routes/_app/flagged'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTagsRoute = AppTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewRoute = AppReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppLocationRoute = AppLocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppForecastRoute = AppForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => AppRoute,
} as any)
const AppFlaggedRoute = AppFlaggedRouteImport.update({
  id: '/flagged',
  path: '/flagged',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/flagged': typeof AppFlaggedRoute
  '/forecast': typeof AppForecastRoute
  '/inbox': typeof AppInboxRoute
  '/location': typeof AppLocationRoute
  '/projects': typeof AppProjectsRoute
  '/review': typeof AppReviewRoute
  '/settings': typeof AppSettingsRoute
  '/tags': typeof AppTagsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/flagged': typeof AppFlaggedRoute
  '/forecast': typeof AppForecastRoute
  '/inbox': typeof AppInboxRoute
  '/location': typeof AppLocationRoute
  '/projects': typeof AppProjectsRoute
  '/review': typeof AppReviewRoute
  '/settings': typeof AppSettingsRoute
  '/tags': typeof AppTagsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/_app/flagged': typeof AppFlaggedRoute
  '/_app/forecast': typeof AppForecastRoute
  '/_app/inbox': typeof AppInboxRoute
  '/_app/location': typeof AppLocationRoute
  '/_app/projects': typeof AppProjectsRoute
  '/_app/review': typeof AppReviewRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/tags': typeof AppTagsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/flagged'
    | '/forecast'
    | '/inbox'
    | '/location'
    | '/projects'
    | '/review'
    | '/settings'
    | '/tags'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/flagged'
    | '/forecast'
    | '/inbox'
    | '/location'
    | '/projects'
    | '/review'
    | '/settings'
    | '/tags'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/dashboard'
    | '/login'
    | '/_app/flagged'
    | '/_app/forecast'
    | '/_app/inbox'
    | '/_app/location'
    | '/_app/projects'
    | '/_app/review'
    | '/_app/settings'
    | '/_app/tags'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tags': {
      id: '/_app/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof AppTagsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/review': {
      id: '/_app/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AppReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/location': {
      id: '/_app/location'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof AppLocationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forecast': {
      id: '/_app/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof AppForecastRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/flagged': {
      id: '/_app/flagged'
      path: '/flagged'
      fullPath: '/flagged'
      preLoaderRoute: typeof AppFlaggedRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppFlaggedRoute: typeof AppFlaggedRoute
  AppForecastRoute: typeof AppForecastRoute
  AppInboxRoute: typeof AppInboxRoute
  AppLocationRoute: typeof AppLocationRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppReviewRoute: typeof AppReviewRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTagsRoute: typeof AppTagsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppFlaggedRoute: AppFlaggedRoute,
  AppForecastRoute: AppForecastRoute,
  AppInboxRoute: AppInboxRoute,
  AppLocationRoute: AppLocationRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppReviewRoute: AppReviewRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTagsRoute: AppTagsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
